version: '3'

networks:
  app:
    driver: bridge

services:
  integration_tests:
    build: ./cmd/integration-tests
    command: "true"
    links:
      - rest-server
      - kafka
    environment:
      - INTEGRATION_TESTS_KAFKA_HOST=kafka:9092
      - INTEGRATION_TESTS_KAFKA_TOPIC=calendar_eventsForSend
      - INTEGRATION_TESTS_REST_SERVER=rest-server:5000
    networks:
      - app

  grpc-server:
    build: ./cmd/grpc-server
    depends_on:
      - postgres
    restart: on-failure
    environment:
      - GRPC_SERVER_HOST=:5900
      - GRPC_SERVER_STORAGE=1
      - GRPC_SERVER_CONN=postgres://calendar:password@postgres/ms_calendar?sslmode=disable
    networks: 
      - app

  rest-server:
    build: ./cmd/rest-server
    depends_on:
      - grpc-server
    hostname: rest-server
    restart: on-failure
    ports:
     - "5000:5000"
    environment:
      - REST_SERVER_GRPC_HOST=grpc-server:5900
      - REST_SERVER_HOST=:5000
      - REST_SERVER_LOGGER=1
    networks: 
      - app

  event-searcher:
    build: ./cmd/event-searcher
    depends_on:
      - grpc-server
      - kafka
    restart: on-failure
    environment:
      - EVENT_SEARCHER_HOST=kafka:9092
      - EVENT_SEARCHER_TOPIC=calendar_eventsForSend      
      - EVENT_SEARCHER_GRPC_HOST=grpc-server:5900
      - EVENT_SEARCHER_DELAY=5
      - EVENT_SEARCHER_LOGGER=1
    networks: 
      - app

  postgres:
    image: postgres:11.1
    restart: on-failure
    environment:
      POSTGRES_USER: calendar
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms_calendar
    volumes:
      - ./scripts/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - app 

  zookeeper:
    image: wurstmeister/zookeeper
    logging:
      driver: none
    networks: 
      - app
  kafka:
    image: 'wurstmeister/kafka'
    hostname: kafka
    environment:
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    links: 
     - zookeeper
    restart: on-failure
    logging:
      driver: none
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app 