// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calendar.proto

package calendarpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	UserId               int32                `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Uuid                 string               `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Message              string               `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Event) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Event) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Event) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type GetResponse struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{2}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type GetAllRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{3}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

func (m *GetAllRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type GetAllResponse struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllResponse) Reset()         { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()    {}
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{4}
}

func (m *GetAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse.Unmarshal(m, b)
}
func (m *GetAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse.Marshal(b, m, deterministic)
}
func (m *GetAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse.Merge(m, src)
}
func (m *GetAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse.Size(m)
}
func (m *GetAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse proto.InternalMessageInfo

func (m *GetAllResponse) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type AddRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{5}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type EditRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditRequest) Reset()         { *m = EditRequest{} }
func (m *EditRequest) String() string { return proto.CompactTextString(m) }
func (*EditRequest) ProtoMessage()    {}
func (*EditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{6}
}

func (m *EditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditRequest.Unmarshal(m, b)
}
func (m *EditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditRequest.Marshal(b, m, deterministic)
}
func (m *EditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditRequest.Merge(m, src)
}
func (m *EditRequest) XXX_Size() int {
	return xxx_messageInfo_EditRequest.Size(m)
}
func (m *EditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditRequest proto.InternalMessageInfo

func (m *EditRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type RemoveRequst struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveRequst) Reset()         { *m = RemoveRequst{} }
func (m *RemoveRequst) String() string { return proto.CompactTextString(m) }
func (*RemoveRequst) ProtoMessage()    {}
func (*RemoveRequst) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{7}
}

func (m *RemoveRequst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRequst.Unmarshal(m, b)
}
func (m *RemoveRequst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRequst.Marshal(b, m, deterministic)
}
func (m *RemoveRequst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRequst.Merge(m, src)
}
func (m *RemoveRequst) XXX_Size() int {
	return xxx_messageInfo_RemoveRequst.Size(m)
}
func (m *RemoveRequst) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRequst.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRequst proto.InternalMessageInfo

func (m *RemoveRequst) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RemoveRequst) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type AddResponse struct {
	Sucess               bool     `protobuf:"varint,1,opt,name=sucess,proto3" json:"sucess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{8}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetSucess() bool {
	if m != nil {
		return m.Sucess
	}
	return false
}

type EditResponse struct {
	Sucess               bool     `protobuf:"varint,1,opt,name=sucess,proto3" json:"sucess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditResponse) Reset()         { *m = EditResponse{} }
func (m *EditResponse) String() string { return proto.CompactTextString(m) }
func (*EditResponse) ProtoMessage()    {}
func (*EditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{9}
}

func (m *EditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditResponse.Unmarshal(m, b)
}
func (m *EditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditResponse.Marshal(b, m, deterministic)
}
func (m *EditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditResponse.Merge(m, src)
}
func (m *EditResponse) XXX_Size() int {
	return xxx_messageInfo_EditResponse.Size(m)
}
func (m *EditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditResponse proto.InternalMessageInfo

func (m *EditResponse) GetSucess() bool {
	if m != nil {
		return m.Sucess
	}
	return false
}

type RemoveResponse struct {
	Sucess               bool     `protobuf:"varint,1,opt,name=sucess,proto3" json:"sucess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveResponse) Reset()         { *m = RemoveResponse{} }
func (m *RemoveResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveResponse) ProtoMessage()    {}
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3d25d49f056cdb2, []int{10}
}

func (m *RemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResponse.Unmarshal(m, b)
}
func (m *RemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResponse.Marshal(b, m, deterministic)
}
func (m *RemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResponse.Merge(m, src)
}
func (m *RemoveResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveResponse.Size(m)
}
func (m *RemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResponse proto.InternalMessageInfo

func (m *RemoveResponse) GetSucess() bool {
	if m != nil {
		return m.Sucess
	}
	return false
}

func init() {
	proto.RegisterType((*Event)(nil), "calendar.Event")
	proto.RegisterType((*GetRequest)(nil), "calendar.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "calendar.GetResponse")
	proto.RegisterType((*GetAllRequest)(nil), "calendar.GetAllRequest")
	proto.RegisterType((*GetAllResponse)(nil), "calendar.GetAllResponse")
	proto.RegisterType((*AddRequest)(nil), "calendar.AddRequest")
	proto.RegisterType((*EditRequest)(nil), "calendar.EditRequest")
	proto.RegisterType((*RemoveRequst)(nil), "calendar.RemoveRequst")
	proto.RegisterType((*AddResponse)(nil), "calendar.AddResponse")
	proto.RegisterType((*EditResponse)(nil), "calendar.EditResponse")
	proto.RegisterType((*RemoveResponse)(nil), "calendar.RemoveResponse")
}

func init() { proto.RegisterFile("calendar.proto", fileDescriptor_e3d25d49f056cdb2) }

var fileDescriptor_e3d25d49f056cdb2 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0x95, 0xb1, 0x71, 0xe9, 0x98, 0xba, 0xd2, 0xaa, 0xa5, 0x96, 0x2f, 0xb5, 0x2c, 0x51, 0x7c,
	0x32, 0x92, 0xa1, 0x52, 0x4b, 0x4f, 0xb4, 0x42, 0xa8, 0x57, 0x2b, 0xa7, 0xdc, 0x0c, 0x3b, 0x41,
	0x48, 0x36, 0x76, 0xd8, 0x35, 0xb7, 0xfc, 0x4f, 0x3e, 0x33, 0x62, 0xbd, 0x1b, 0x2f, 0x24, 0x0a,
	0xe1, 0xc6, 0xec, 0xbc, 0x37, 0x6f, 0xde, 0x1b, 0x0c, 0xee, 0x3a, 0xcb, 0x71, 0x47, 0xb3, 0x7d,
	0x5c, 0xed, 0x4b, 0x5e, 0x92, 0x9e, 0xaa, 0xfd, 0xef, 0x9b, 0xb2, 0xdc, 0xe4, 0x38, 0x16, 0xef,
	0xab, 0xfa, 0x6e, 0xcc, 0xb7, 0x05, 0x32, 0x9e, 0x15, 0x55, 0x03, 0x0d, 0x1f, 0xa0, 0xbb, 0x38,
	0xe0, 0x8e, 0x93, 0x01, 0xd8, 0x35, 0xc3, 0xfd, 0x7f, 0xea, 0x19, 0x81, 0x11, 0x75, 0x53, 0x59,
	0x11, 0x02, 0x56, 0x5d, 0x6f, 0xa9, 0xd7, 0x09, 0x8c, 0xe8, 0x63, 0x2a, 0x7e, 0x93, 0x18, 0x2c,
	0x9a, 0x71, 0xf4, 0xcc, 0xc0, 0x88, 0x9c, 0xc4, 0x8f, 0x1b, 0x91, 0x58, 0x89, 0xc4, 0x37, 0x4a,
	0x24, 0x15, 0x38, 0xe2, 0xc1, 0x87, 0x02, 0x19, 0xcb, 0x36, 0xe8, 0x59, 0x62, 0x8c, 0x2a, 0xc3,
	0x5f, 0x00, 0x4b, 0xe4, 0x29, 0xde, 0xd7, 0xc8, 0xae, 0xda, 0x21, 0x9c, 0x82, 0x23, 0x98, 0xac,
	0x2a, 0x77, 0x0c, 0xc9, 0x10, 0xba, 0x78, 0xf4, 0x21, 0x98, 0x4e, 0xf2, 0x39, 0x7e, 0x8e, 0x44,
	0xd8, 0x4b, 0x9b, 0x6e, 0x38, 0x82, 0x4f, 0x4b, 0xe4, 0xf3, 0x3c, 0xbf, 0x20, 0x19, 0xfe, 0x06,
	0x57, 0x01, 0xa5, 0xc2, 0x08, 0x6c, 0x31, 0x83, 0x79, 0x46, 0x60, 0xbe, 0x26, 0x21, 0xdb, 0xe1,
	0x04, 0x60, 0x4e, 0xa9, 0x12, 0x78, 0xe7, 0x62, 0x53, 0x70, 0x16, 0x74, 0xcb, 0xaf, 0x64, 0xcd,
	0xa0, 0x9f, 0x62, 0x51, 0x1e, 0xf0, 0xc8, 0xbb, 0x32, 0xc0, 0x21, 0x38, 0x62, 0x4d, 0x69, 0x6f,
	0x00, 0x36, 0xab, 0xd7, 0xc8, 0x98, 0xa0, 0xf6, 0x52, 0x59, 0x85, 0x3f, 0xa0, 0xdf, 0x2c, 0x76,
	0x01, 0x17, 0x81, 0xab, 0x56, 0x79, 0x1b, 0x99, 0x3c, 0x76, 0xc0, 0xfd, 0x27, 0xed, 0x08, 0x37,
	0x8c, 0x24, 0x60, 0x2e, 0x91, 0x93, 0x2f, 0xad, 0xcd, 0xf6, 0x5f, 0xe1, 0x7f, 0x3d, 0x7b, 0x95,
	0xe3, 0xff, 0x80, 0xdd, 0x5c, 0x88, 0x7c, 0x3b, 0x01, 0xb4, 0xc7, 0xf5, 0xbd, 0x97, 0x0d, 0x49,
	0x4e, 0xc0, 0x9c, 0x53, 0xaa, 0x0b, 0xb6, 0x27, 0xd3, 0x05, 0xf5, 0x84, 0x7e, 0x82, 0x75, 0x4c,
	0x82, 0x68, 0x6d, 0xed, 0x64, 0xfe, 0xe0, 0xfc, 0x59, 0xd2, 0x66, 0x60, 0x37, 0xc1, 0x10, 0x0d,
	0xa1, 0x5f, 0x4d, 0x5f, 0xf3, 0x34, 0xc2, 0xbf, 0xfd, 0x5b, 0x50, 0xad, 0x6a, 0xb5, 0xb2, 0xc5,
	0x07, 0x36, 0x79, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xf2, 0xc8, 0x3e, 0xef, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalendarEventsClient is the client API for CalendarEvents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalendarEventsClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error)
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Edit(ctx context.Context, in *EditRequest, opts ...grpc.CallOption) (*EditResponse, error)
	Remove(ctx context.Context, in *RemoveRequst, opts ...grpc.CallOption) (*RemoveResponse, error)
}

type calendarEventsClient struct {
	cc *grpc.ClientConn
}

func NewCalendarEventsClient(cc *grpc.ClientConn) CalendarEventsClient {
	return &calendarEventsClient{cc}
}

func (c *calendarEventsClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/calendar.CalendarEvents/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarEventsClient) GetAll(ctx context.Context, in *GetAllRequest, opts ...grpc.CallOption) (*GetAllResponse, error) {
	out := new(GetAllResponse)
	err := c.cc.Invoke(ctx, "/calendar.CalendarEvents/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarEventsClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/calendar.CalendarEvents/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarEventsClient) Edit(ctx context.Context, in *EditRequest, opts ...grpc.CallOption) (*EditResponse, error) {
	out := new(EditResponse)
	err := c.cc.Invoke(ctx, "/calendar.CalendarEvents/Edit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarEventsClient) Remove(ctx context.Context, in *RemoveRequst, opts ...grpc.CallOption) (*RemoveResponse, error) {
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, "/calendar.CalendarEvents/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalendarEventsServer is the server API for CalendarEvents service.
type CalendarEventsServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetAll(context.Context, *GetAllRequest) (*GetAllResponse, error)
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Edit(context.Context, *EditRequest) (*EditResponse, error)
	Remove(context.Context, *RemoveRequst) (*RemoveResponse, error)
}

// UnimplementedCalendarEventsServer can be embedded to have forward compatible implementations.
type UnimplementedCalendarEventsServer struct {
}

func (*UnimplementedCalendarEventsServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedCalendarEventsServer) GetAll(ctx context.Context, req *GetAllRequest) (*GetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedCalendarEventsServer) Add(ctx context.Context, req *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedCalendarEventsServer) Edit(ctx context.Context, req *EditRequest) (*EditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Edit not implemented")
}
func (*UnimplementedCalendarEventsServer) Remove(ctx context.Context, req *RemoveRequst) (*RemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Remove not implemented")
}

func RegisterCalendarEventsServer(s *grpc.Server, srv CalendarEventsServer) {
	s.RegisterService(&_CalendarEvents_serviceDesc, srv)
}

func _CalendarEvents_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarEventsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.CalendarEvents/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarEventsServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarEvents_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarEventsServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.CalendarEvents/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarEventsServer).GetAll(ctx, req.(*GetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarEvents_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarEventsServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.CalendarEvents/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarEventsServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarEvents_Edit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarEventsServer).Edit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.CalendarEvents/Edit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarEventsServer).Edit(ctx, req.(*EditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarEvents_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequst)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarEventsServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.CalendarEvents/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarEventsServer).Remove(ctx, req.(*RemoveRequst))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalendarEvents_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calendar.CalendarEvents",
	HandlerType: (*CalendarEventsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _CalendarEvents_Get_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _CalendarEvents_GetAll_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _CalendarEvents_Add_Handler,
		},
		{
			MethodName: "Edit",
			Handler:    _CalendarEvents_Edit_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _CalendarEvents_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calendar.proto",
}
